export const propertyKeys = [
  {
    key: 'like_count',
    name: 'いいね',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'comment_count',
    name: 'コメント',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'share',
    name: 'シェア',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'save',
    name: '保存',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'reach',
    name: 'リーチ',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'reach_follower',
    name: 'フォロワー',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'reach_non_follower',
    name: 'フォロワー以外',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'performed_account',
    name: 'アクションを実行したアカウント',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'follower',
    name: 'フォロワー',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'non_follower',
    name: 'フォロワー以外',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'impression',
    name: 'インプレッション',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'home',
    name: 'ホーム',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'profile',
    name: 'プロフィール',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'hashtag',
    name: 'ハッシュタグ',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'others',
    name: 'その他',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'profile_activity',
    name: 'プロフィールのアクティビティ',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'profile_access',
    name: 'プロフィールへのアクセス',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'followers',
    name: 'フォロー数',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'taps',
    name: '［メールを送信］ボタンのタップ数',
    hasChildren: false,
    isChildren: true,
  },
];

export const mainPropertyKeys = [
  {
    key: 'play_count',
    name: '再生',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'like_count',
    name: 'いいね',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'comment_count',
    name: 'コメント',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'share',
    name: 'シェア',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'save',
    name: '保存',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'play_time_sum',
    name: '合計再生時間',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'play_time_sum_hour',
    name: '時間',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'play_time_sum_min',
    name: '分',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'play_time_sum_sec',
    name: '秒',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'avg_audience_time',
    name: '平均視聴時間',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'full_video',
    name: '動画をフル視聴',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'new_follower',
    name: '新しいフォロワー',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'traffic_source',
    name: 'トラフィックソース',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'recommendation',
    name: 'おすすめ',
    hasChildren: false,
    isChildren: true,
  },
];
export const audiencePropertyKeys = [
  {
    key: 'total_views',
    name: '総視聴数',
    hasChildren: false,
    isChildren: false,
  },
  {
    key: 'gender',
    name: '性別',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'male',
    name: '男性',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'female',
    name: '女性',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'age',
    name: '年齢',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'age_little',
    name: '18 - 24',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'age_young',
    name: '25 - 34',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'age_middle',
    name: '35 - 44',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'age_little_old',
    name: '45 - 54',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'age_old',
    name: '55 +',
    hasChildren: false,
    isChildren: true,
  },
  {
    key: 'top_location',
    name: '上位のロケーション',
    hasChildren: true,
    isChildren: false,
  },
  {
    key: 'japan',
    name: '日本',
    hasChildren: false,
    isChildren: true,
  },
];
